### ISSUE TITLE
a question about thread_fence

### ISSUE THREAD

**Issue by UncP** [rmind/thmap#2]
```c
	atomic_thread_fence(memory_order_stores); // this affects line below
	node->state = s; // atomic store
```

```c
	node_insert(child, other_slot, target);

	/*
	 * Insert the intermediate node into the parent node.
	 * It becomes the new parent for the our new leaf.
	 *
	 * Ensure that stores to the child (and leaf) reach the
	 * global visibility before it gets inserted to the parent.
	 */
	atomic_thread_fence(memory_order_stores); // this seems to affect the line above
	parent->slots[slot] = THMAP_GETOFF(thmap, child);

```
how does `memory_order_stores` and `memory_order_loads` affect the code?

**Comment by alexk99** [comment]
I would like to join to the question and also put it in a bit different way. Why do you use full memory barriers instead acquire/release barriers?
P.S.
UncP, you may want to look at this series of articles written by Preshing http://preshing.com/20120612/an-introduction-to-lock-free-programming/ and just 
I think it is one of the best on the topic.

**Comment by rmind** [comment]
> ```c
> 	atomic_thread_fence(memory_order_stores); // this affects line below
> 	node->state = s; // atomic store
> ```
It prevents the stores inside the critical path from being re-ordered to occur outside the critical path. It is necessary for the same reason why a textbook implementation of the mutex release would need a memory fence (either store or release; although on x86/TSO, just the compiler barrier would be sufficient).

> 
> ```c
> 	node_insert(child, other_slot, target);
> 
> 	/*
> 	 * Insert the intermediate node into the parent node.
> 	 * It becomes the new parent for the our new leaf.
> 	 *
> 	 * Ensure that stores to the child (and leaf) reach the
> 	 * global visibility before it gets inserted to the parent.
> 	 */
> 	atomic_thread_fence(memory_order_stores); // this seems to affect the line above
> 	parent->slots[slot] = THMAP_GETOFF(thmap, child);
> ```
I think the comment explains it. The readers must see the consistent child node, before it gets visible (accessible) through the parent slot, therefore we need a store fence here. Do you have a more specific question or see a problem in the code?

> I would like to join to the question and also put it in a bit different way. Why do you use full memory barriers instead acquire/release barriers?

Because I am used to classic read (load) and write (store) memory barriers/fences which have been clearly defined and used for decades in the UNIX-like kernels (e.g. Solaris, Linux, NetBSD).

It is a mystery why C++11/C11 committees decided to provide only the acquire/release semantics (which are also very poorly defined in the standard document and there is a bit of debate about the exact promises) and not build on the prior art. Anyway, I define new `memory_order_stores` and `memory_order_loads` which are, for now, emulated as full barriers, but this can be optimised.

**Comment by UncP** [comment]
I am wondering how to use `atomic_thread_fence(memory_order_stores)`, it seems that `atomic_thread_fence(memory_order_stores)` can protect both the code above it and below it.
In the first case, you use it to make sure that the `node->state`, which is set **after** the memory barrier will be seen by other threads,
in the second case, you use it to make sure that child, which is set **before** the memory barrier, will be fully seen by other threads.

Which part `atomic_thread_fence(memory_order_stores)` will affect, the code before this barrier or the code after it. Also does `memory_order_loads` works the same as `stores`?


```c
node->state = s; // atomic store
atomic_thread_fence(memory_order_stores);

parent->slots[slot] = THMAP_GETOFF(thmap, child);
atomic_thread_fence(memory_order_stores);
```

I switched the sequence for each case, is the code above ok?

**Comment by alexk99** [comment]
> They affect the loads/stores before and after the fence, both ways. 

Do you really need both way fences?

>Unlike the acquire/release fences, which are one-way barriers.

It's not an entirely correct statement, since they work like both way fences but only for the particular load (in case of acquire) located right before the fence and for the store located right after the release fence.
So, can the payload/guard model be used in your code? Will the code work correctly if memory_order_loads fences are replaced with acqure fences and memory_order_stores with releases? Since they are cheaper on some systems than full barriers, it will improve the performance a little bit, no?

**Comment by rmind** [comment]
> > They affect the loads/stores before and after the fence, both ways.
> 
> Do you really need both way fences?
> 

In this case, yes.

> > Unlike the acquire/release fences, which are one-way barriers.
> 
> It's not an entirely correct statement, since they work like both way fences but only for the particular load (in case of acquire) located right before the fence and for the store located right after the release fence.

No, they affect **all** loads and stores before/after the fence. Even if you use C11/C++11 atomic synchronisation semantics (as opposed to fence vs fence synchronisation), it basically impacts all loads/stores because that is how CPUs generally work.

> So, can the payload/guard model be used in your code? Will the code work correctly if memory_order_loads fences are replaced with acqure fences and memory_order_stores with releases? Since they are cheaper on some systems than full barriers, it will improve the performance a little bit, no?

No, they have different semantics. However, on TSO architectures, including x86, `memory_order_stores` can just be a compiler-level barrier (like memory_order_acquire/memory_order_release), so it does not cost anything.

**Comment by UncP** [comment]
Thanks, I think I know what you mean. @rmind

Also, I think acquire-release should be enough for your thmap.

**Comment by rmind** [comment]
> > No, they affect all loads and stores before/after the fence. Even if you use C11/C++11 atomic >synchronisation semantics (as opposed to fence vs fence synchronisation), it basically impacts all >loads/stores because that is how CPUs generally work.
> 
> I was talking about acquire/release fences. According to this http://preshing.com/20120913/acquire-and-release-semantics/ they prevent reordering (both ways) all operation after/before the fence with single load/store operation before/after the fence.

I do not think your interpretation is right. The acquire/release fences also have an affect for **all**, just one-way. I think you might be confusing fence-fence synchronisation with fence-atomic.

> You are right. My question was is it that single operation after/before the fence in acquire/release semantic not enough to your needs.

If your question is whether thmap can be converted to use acquire/release semantics, then -- most likely yes.  Just have not had time to pursue this path, as I implemented thmap relatively recently.  Also, the use of memory fences needs to be carefully verified and stress tested, preferably on different CPUs (e.g. you can notice that certain race conditions do not trigger on a slightly older CPUs, because they just don't do such agressive re-ordering and the race windows in the code are too small).  It is very easy to write a lock-free algorithm which works 99% of the time, but breaks in very weird and hard to debug ways during a serious load.

> I was thinking about different architectures, where, again according to Preshing, full fence is more expencive.

I am very well aware of the memory barrier costs.

**Comment by rmind** [comment]
Update: I just converted thmap to C11 acquire/release fences.

@alexk99: Also, I retract my statement that acquire/release fences are "one-way" i.e. I agree with you it is not entirely correct or at least confusing. However, I think we can call these fences as **asymmetric**.
